include(ExternalProject)
include (${CMAKE_CURRENT_SOURCE_DIR}/BuildScripts/CMake/BuildGoogleTestFromSources.cmake)
function(ProvideGoogleTests)
    find_package( GTest QUIET)
    if ( NOT GTEST_FOUND )
        message ("--------------------------------------------------------------------------------")
        message ("                                                                                ")
        message (" Gtest Needs to be built from source. ")
        message ("                                                                                ")
        message ("--------------------------------------------------------------------------------")
        BuildGoogleTestFromSources()
    else()
        message ("--------------------------------------------------------------------------------")
        message ("                                                                                ")
        message (" Not Building Google Tests since these are installed on the development system. ")
        message ("                                                                                ")
        message ("--------------------------------------------------------------------------------")
        enable_testing()
        find_package(GTest REQUIRED)
    endif( NOT GTEST_FOUND )
 
endfunction(ProvideGoogleTests)
