name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Diagnostics
      run: echo $(pwd) && echo "" && echo $(ls)
      working-directory: ${{runner.workspace}}/build
    - name: configure
      run: mkdir build && cd build && cmake ..
      working-directory: ${{runner.workspace}}/build
